#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================
domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
#siwi launch on boot entfernt
#launch_on_boot=$YNH_APP_ARG_LAUNCH_ON_BOOT
open_webserver_port=$YNH_APP_ARG_OPEN_WEBSERVER_PORT

app=$YNH_APP_INSTANCE_NAME
#=================================================
# GLOBAL VARS
#=================================================
final_path=/var/www/$app

test ! -e "$final_path" || ynh_die "This path already contains a folder"

# Register (book) web path
ynh_webpath_register "$app" "$domain" "$path_url"


#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression --message="Storing installation settings..." --time --weight=1

ynh_app_setting_set --app=$app --key=domain --value=$domain
ynh_app_setting_set "$app" domain "$domain"
ynh_app_setting_set "$app" path_url "$path_url"
ynh_app_setting_set "$app" final_path "$final_path"
#siwi launch on boot entfernt
#ynh_app_setting_set "$app" launch_on_boot "$launch_on_boot"
ynh_app_setting_set "$app" open_webserver_port "$open_webserver_port"

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN A PORT
#=================================================

ynh_script_progression --message="Finding an available port......" --time --weight=1
#siwi check port Behandlung
port=$(ynh_find_port --port=8080)
ynh_app_setting_set --app=$app --key=port --value=$port

if [ "$open_webserver_port" -eq 1 ]
then
    ynh_script_progression --message="Configuring firewall..." --time --weight=1
    ynh_exec_warn_less yunohost firewall allow --no-upnp TCP $port
fi


#=================================================
# CREATE KODI USER
#=================================================
ynh_system_user_create "$app" "$final_path"
mkdir "$final_path"
chown -R "$app":"$app" "$final_path"
usermod -a -G cdrom,audio,video,plugdev,users,dialout,dip,input,netdev "$app"

# Create a system user
# s.w. wahrscheinlich geht alles da oben mit dieser Zeile (zu testen, insbesondere user und group von finalpath)
# ynh_system_user_create --username="$app" --home_dir="$final_path" --groups="cdrom,audio,video,plugdev,users,dialout,dip,input,netdev"

#=================================================
# ADD SYSTEMD CONFIG
#=================================================
#siwi launch on boot entfernt
#ynh_add_systemd_config

#if [ "$launch_on_boot" -eq 0 ]
#then
#    systemctl disable "$app"
#fi


#=================================================
# INSTALL DEPENDENCIES AND KODI
#=================================================
ynh_script_progression --message="Installing Kodi and dependencies..." --time --weight=1
ynh_install_app_dependencies $pkg_dependencies

#=================================================
# X11 SETTINGS
#=================================================
ynh_replace_string "allowed_users=console" "allowed_users=anybody" /etc/X11/Xwrapper.config


#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================
yunohost service add "$app" --log "$final_path/.kodi/temp/kodi.log"


#=================================================
# CONTROL WEB INTERFACE
#=================================================
mkdir -p "$final_path/.kodi/userdata/"
cp ../conf/advancedsettings.xml "$final_path/.kodi/userdata/advancedsettings.xml"

#siwi: das ist vermutlich garnicht notwendig?
#mkdir -p "$final_path/.kodi/addons/"
#if [[ $arch != arm*  ]]; then
#     ynh_setup_source --dest_dir="$final_path/.kodi/addons/" --source_id="arm-chorus2" 
#fi

chown -R "$app":"$app" "$final_path"



#=================================================
# NGINX
#=================================================
finalnginxconf="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_backup_if_checksum_is_different "$finalnginxconf"
cp ../conf/nginx.conf "$finalnginxconf"

if [ "$path_url" == "/" ]; then
    ynh_replace_string "__PATH__/" "/" "$finalnginxconf"
else
    ynh_replace_string "__PATH__" "$path_url" "$finalnginxconf"
fi

ynh_app_setting_set "$app" protected_uris "/"

domainregex=$(echo "$domain" | sed 's/-/\%&/g')
ynh_app_setting_set "$app" skipped_regex "$domainregex/jsonrpc.*$,$domainregex/image.*$"

siwi ab hier ist aktualisiert

#=================================================
# NGINX CONFIGURATION
#=================================================
#siwi to be checked
ynh_script_progression --message="Configuring NGINX web server..." --time --weight=1

### `ynh_add_nginx_config` will use the file conf/nginx.conf

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# SETUP SYSTEMD
#=================================================
#siwi to be checked
ynh_script_progression --message="Configuring a systemd service..." --time --weight=1

ynh_add_systemd_config

#=================================================
# GENERIC FINALIZATION
#=================================================
# SETUP LOGROTATE
#=================================================
#siwi to be checked
ynh_script_progression --message="Configuring log rotation..." --time --weight=1

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
#siwi to be checked
ynh_script_progression --message="Integrating service in YunoHost..." --time --weight=1

yunohost service add $app --description="A short description of the app" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --time --weight=1

ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# SETUP SSOWAT
#=================================================
ynh_script_progression --message="Configuring permissions..." --time --weight=1

# Make app public if necessary
#if [ $is_public -eq 1 ]
#then
#	# Everyone can access the app.
#	# The "main" permission is automatically created before the install script.
#	ynh_permission_update --permission="main" --add="visitors"
#fi

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading NGINX web server..." --time --weight=1

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --time --last
